### PR TITLE
chore(deps): update robotjs to use prebuilds during npm install

### PR DESCRIPTION
**Pull request by csett86**

### CODE REVIEW

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Shall we make a .1 release now?

**Comment by csett86** [comment]
Have you had any further input from 8x8 internal groups or team on 3.0.0 any any issues? If yes, I would fix them and then do the 3.0.1, if there is no feedback (yet), then I would directly do the 3.0.1

**Comment by saghul** [comment]
No feedback yet, I'd so a 3.0.1 so we don't run into prebuilt issues.

**Comment by csett86** [comment]
Agree, then here we go: https://github.com/jitsi/jitsi-meet-electron-sdk/pull/155

**Pull request merged**
