### PR TITLE
ci: autopublish to npm on every commit

### PR DESCRIPTION
**Pull request by csett86**
Closes: #258

### CODE REVIEW

**Comment by csett86** [comment]
@saghul, please review

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
I removed branch protection since the that prevents autopublish from working.

**Comment by csett86** [comment]
Now the npm whoami is failing:

https://github.com/jitsi/jitsi-meet-electron-sdk/runs/7669322683?check_suite_focus=true#step:6:23

Any idea how to fix that as well, @saghul?

**Comment by csett86** [comment]
I already checked https://github.com/jitsi/eslint-config-jitsi/blob/master/.github/workflows/autopublish.yml and did not spot any difference

**Comment by saghul** [comment]
Hum, maybe it needs a new npm auth token. I'll update it.

**Comment by saghul** [comment]
Updated. Can you try again?

**Comment by csett86** [comment]
I think I have an idea: #265

**Comment by csett86** [comment]
Ok, still not enough, now failing on the npm install in the autopublisher, will check later

**Comment by saghul** [comment]
Thanks mate!

**Comment by csett86** [comment]
I did a deep dive and was unable to get it to work with the jitsi/autopublisher due to the binary dependencies.

Now switched to the original autopublisher and added the npm publish steps manually afterwards: #266 

This time I also tested it successfully with dry-run flags: https://github.com/jitsi/jitsi-meet-electron-sdk/actions/runs/2805064709

**Comment by csett86** [comment]
Its working as tested, I directly proposed it to @jitsi/robotjs as well: https://github.com/jitsi/robotjs/pull/13

**Pull request merged**
