### PR TITLE
Drop support for WifiStats

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by hristoterezov** [comment]
Why are we dropping wifi stats?

**Review by hristoterezov — CHANGES_REQUESTED** [review]
Please add some details? Is it not working anymore? We don't need it anymore?

**Comment by saghul** [comment]
We don't use it / need it anymore indeed.

**Review by hristoterezov — APPROVED** [review]
Let's remove it from the other projects too!

**Pull request merged**
