### PR TITLE
chore(build) prevent accidental pushes to master

### PR DESCRIPTION
**Pull request by saghul**
The auto-release bot should still work since it doesn't install the
pre-commit hook.

Sample run:

```
$ git push --dry-run 
You can't commit directly to master branch
husky - pre-push hook exited with code 1 (error)
error: failed to push some refs to 'github.com:jitsi/jitsi-meet-electron-utils.git'
```

### CODE REVIEW

**Review by horymury — APPROVED** [review]

**Comment by saghul** [comment]
@csett86 do you reckon this would work for you?

**Comment by csett86** [comment]
Are you sure that the checkout action (https://github.com/jitsi/jitsi-meet-electron-sdk/blob/master/.github/workflows/ci.yml#L48) does not install the precommit hook?

i could not find anything pointing to that…

**Comment by saghul** [comment]
Reasonably sure, since I added that step myself to my auto-publish plugin, which is what created trouble, so I think it's safe to say checking it out doesn't npm i.

**Comment by saghul** [comment]
You can also check in any of the runs: https://github.com/jitsi/jitsi-meet-electron-sdk/runs/8034378226?check_suite_focus=true

**Review by csett86 — APPROVED** [review]
Then lets go for this

**Comment by csett86** [comment]
Fails in a different place, unfortunately: https://github.com/jitsi/jitsi-meet-electron-sdk/runs/8035799191?check_suite_focus=true

**Comment by saghul** [comment]
FML, `npm publish` runs the `prepare` step too... Let me check if we can skip it...

**Pull request merged**
