### PR TITLE
Switch to prebuildify

### PR DESCRIPTION
**Pull request by csett86**
bundles the prebuilds in the npm package, saving extra downloads and
recommended by prebuild maintainers.

### CODE REVIEW

**Review by saghul — APPROVED** [review]
Nice reduction in package-lock!

**Comment by csett86** [comment]
Had to rebase it to master, no changes otherwise

**Comment by csett86** [comment]
And yes, @saghul, prebuild has around 317 dependencies, while prebuildify has 31, so thats a nice reduction of dependencies, indeed.

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
re-approved!

**Pull request merged**
