### PR TITLE
ci: publish release to npm

### LINKED ISSUE #144: Automate publishing to NPM with GH actions
adding the npm registry to the `setup-node` step and a 

    npm publish

with npm token via secret

    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

and guarded with the release published conditions should do it according to: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry

### PR DESCRIPTION
**Pull request by csett86**
Requires npm access token in secret `NPM_TOKEN`

Closes #144

### CODE REVIEW

**Comment by saghul** [comment]
We already have a PUBLISH_TOKEN secret. Let's try that?

**Comment by csett86** [comment]
The PUBLISH_TOKEN is a github API token, I would assume (as its used to publish to GH releases), here we need a npmjs access token. Even though npmjs is nowadays owned by github, I could not find any reference that github tokens works to publish to npm. Did I miss anything?

**Comment by saghul** [comment]
Ah wait, you're right.

**Comment by saghul** [comment]
Done.

**Review by saghul — APPROVED** [review]

**Pull request merged**
