### PR TITLE
popupconfig: adjust to new-window event replacement

### PR DESCRIPTION
**Pull request by csett86**
See https://www.electronjs.org/docs/latest/breaking-changes#removed-webcontents-new-window-event

### CODE REVIEW

**Comment by csett86** [comment]
@saghul please review if you have time

**Comment by saghul** [comment]
I'd like @quitrk to take a look since we need to integrate with other window handlers in 8x8 apps and we need to keep that working.

**Comment by csett86** [comment]
@quitrk can you please take a look? Thanks in advance!

**Comment by csett86** [comment]
@quitrk as the new-window event is removed since Electron 22 (and we are now at 25), and the current popupsconfig code still relies on it, can you please take a look if this replacement PR looks good from your perspective?

**Comment by quitrk** [comment]
@csett86 looks good to me

**Review by quitrk — APPROVED** [review]

**Comment by csett86** [comment]
Thank you @quitrk

**Pull request merged**
